<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>11ed49d3-2ad3-4921-b55f-687d667d967f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.hvr-float-shadow.ff-gotham-bold.-s-16.t-t-upper.co-white.d-grey.pl-30.pr-30.pt-10.pb-10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aea49cee-c67e-4e14-9de1-f0b1177a6b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>submitted=true</value>
      <webElementGuid>806118e3-341e-4b74-84af-851015b1316b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn hvr-float-shadow ff-gotham-bold -s-16 t-t-upper co-white d-grey pl-30 pr-30 pt-10 pb-10</value>
      <webElementGuid>082cc9ed-d72e-4afd-beed-4e0310d019f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>823fdcd2-a825-4c7b-b9c2-0a36b62812fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login </value>
      <webElementGuid>0240871e-6caa-4513-8c96-9a16a3dce424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope sidebar-is-reduced sidebar-is-expanded&quot;]/div[1]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;limiter ng-scope&quot;]/div[@class=&quot;container-login100&quot;]/div[@class=&quot;col-md-4 com-xs-4 login-form reflection--form&quot;]/form[@class=&quot;create_user_form login100-form validate-form ng-pristine ng-valid-email ng-invalid ng-invalid-required ng-valid-pattern&quot;]/div[@class=&quot;form-group mt-40 clearfix&quot;]/div[@class=&quot;col-sm-12 p-0&quot;]/div[@class=&quot;row m-0&quot;]/div[@class=&quot;col-sm-4 p-0&quot;]/button[@class=&quot;btn hvr-float-shadow ff-gotham-bold -s-16 t-t-upper co-white d-grey pl-30 pr-30 pt-10 pb-10&quot;]</value>
      <webElementGuid>8c189da3-ca34-4389-b782-5e7f1bd383fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>39020b5b-cacf-42e9-b208-118e3703115b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/following::button[1]</value>
      <webElementGuid>686a6542-7919-489f-9044-427bc69f8f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::button[1]</value>
      <webElementGuid>527b7fb9-f3b2-4048-b157-79658816de00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-or-'])[1]/preceding::button[1]</value>
      <webElementGuid>a8245be4-a82f-4038-a4da-d0ca0bac382c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login with'])[1]/preceding::button[1]</value>
      <webElementGuid>9290cf96-9c79-4aa6-965a-2b1cc8a3c62d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>0224ba42-bab4-4f5b-ae1f-5f611042c0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a5a95a34-a30a-4d10-9071-ff2b60d2a785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Login ' or . = ' Login ')]</value>
      <webElementGuid>4c6379cf-67d8-4a33-9207-047391ed587b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
